### ISSUE TITLE
Excellent job but it needs to be complete

### ISSUE THREAD

**Issue by funlw65** [polyelectronics/pikdev#1]
And for that, cpik has to be "ported". As I remember, it uses qmake from qt4?

**Comment by funlw65** [comment]
Never mind, it works also with qmake from qt5...

BTW, if the original archive of cpik does not  compile, mine does because it contains a modification made by Alain, don't know why he did not updated his last archive... You can compare them... Below is the link:

https://drive.google.com/file/d/1XQFLJaUlFY9ZWR-iHTjABASdh1GyDtoD/view?usp=sharing

**Comment by polyelectronics** [comment]
Hello @funlw65. I appreciate your observation, but this repository only contains the PikDev IDE (GUI and command line pkp).
I need to create another repository with the [Cpik C compiler for PIC18 devices](http://pikdev.free.fr/download-cpik.php3), like the [PikLoops](https://github.com/polyelectronics/pikloops) utility.
Give me time to review the tar.gz and I promise to upload it to a new repository.
Cheers.
