### ISSUE TITLE
Editor's highlighted current line ...

### ISSUE THREAD

**Issue by funlw65** [polyelectronics/pikdev#2]
I have this problem with the highlighted current line in the editor, it is unusable in dark themes (you can't see what you edit) and there is no option in configuration dialog to deactivate the highlighting or change its colors. If you cannot reproduce the problem, I can provide a screenshot.

**Comment by polyelectronics** [comment]
Hello @funlw65, I see the problem is the highlighted line in editor only has one color (yellow 60% lighter).
[Line 145 in codeeditor/CodeEditor.cpp ](https://github.com/polyelectronics/pikdev/blob/9de7b930955e434a37da6c83df34b64fe57e34bb/src/codeeditor/CodeEditor.cpp#L145) has to be changed accroding to user theme.

```
void CodeEditor::highlightCurrentLine ()
{
    highlightCurrentLine_ (QColor (Qt::yellow).lighter (160));
}

void CodeEditor::highlightCurrentLine_ (__attribute__ ((unused)) const QColor& lineColor)
{
    QList<QTextEdit::ExtraSelection> extraSelections;

    if (! isReadOnly ())
      {
        QTextEdit::ExtraSelection selection;
	QPalette p = this->palette ();
	QColor c = p.color (QPalette::Text);

	if (c.lightness () < 100)
	  selection.format.setBackground (QColor (Qt::yellow).lighter (160));	
	else
	  selection.format.setBackground (QColor (Qt::gray).darker (160));
	
        selection.format.setProperty (QTextFormat::FullWidthSelection, true);
        selection.cursor = textCursor ();
        selection.cursor.clearSelection ();
        extraSelections.append (selection);
      }

    setExtraSelections (extraSelections);
}
```

**Comment by funlw65** [comment]
Working great, thank you!
